import Head from 'next/head'
import Layout from 'layouts/layout'

export default function About() {
    return (
        <div className='w-full h-full'>
            <Head>
                <title>About | Persistent Layouts with Next Themes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <span className='text-black dark:text-white'>about</span>
        
        </div>
    )
}

About.getLayout = function getLayout(page) {
    return (
        <Layout>
            {page}
        </Layout>
    )
}